### PR TITLE
add struct tag

### PR DESCRIPTION
**Pull request by ycheng**
ref: https://golang.org/pkg/reflect/#StructTag

### CODE REVIEW

**Comment by codingsince1985** [comment]
Thank you @ycheng. It would be great if you can also provide an example of using tagged elements.

**Comment by ycheng** [comment]
@codingsince1985, I learn tag from https://github.com/jessevdk/go-flags. currently still no shorter example. Maybe we should add a part for reflect.

**Comment by codingsince1985** [comment]
@ycheng, I agree. Freestyle tag + reflect is a pretty advanced topic, IMO. People use json tag, which hasn't been covered yet, more often.

**Comment by ycheng** [comment]
yes, json tag is the best candidate for example here !

**Comment by codingsince1985** [comment]
Close for now.

**Pull request closed without merging**
